version: "2"



run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:


linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  disable:
    - depguard
    - gosec
    - funlen
    - lll
    - gocyclo
    - gocritic
    - unparam
    - ineffassign
    - prealloc

