version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - misspell
    - nakedret
    - rowserrcheck
    - staticcheck
    - unconvert
    - unused
    - whitespace
  disable:
    - depguard
    - gosec
    - gocyclo
    - gocritic
    - prealloc