name: Build and Publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Trigger on tags with semantic versioning

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20 # Use the Go version you need
        
    - name: Build
      run: go build -o fetch-k8s-cert
      
    - name: Package for Debian
      run: |
        mkdir -p debian/fetch-k8s-cert/usr/local/bin
        cp fetch-k8s-cert debian/fetch-k8s-cert/usr/local/bin
        dpkg-deb --build debian
        mv debian.deb fetch-k8s-cert.deb
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    
    - name: Upload Release Assets
      id: upload-release-assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: |
          fetch-k8s-cert
          fetch-k8s-cert.deb
        asset_name: |
          fetch-k8s-cert
          fetch-k8s-cert.deb
        asset_content_type: application/octet-stream
