name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Trigger on tags with semantic versioning

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: ./.github/workflows/build.yml

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "*.deb"
